# Generated by Django 3.2.7 on 2023-04-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='reps',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
