# Generated by Django 3.2.7 on 2023-04-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0003_auto_20230417_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='reps',
            field=models.IntegerField(),
        ),
    ]
