# Generated by Django 3.2.7 on 2023-05-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0006_alter_entry_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('image_url', models.TextField()),
            ],
        ),
    ]
