# Generated by Django 3.2.7 on 2023-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0008_rename_days_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='days',
            field=models.CharField(choices=[('SUN', 'SUN'), ('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT')], default=1, max_length=9),
            preserve_default=False,
        ),
    ]
