# Generated by Django 3.2.7 on 2023-05-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0009_exercises_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
    ]
