# Generated by Django 3.2.7 on 2023-05-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0010_delete_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SUN', 'SUN'), ('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT')], max_length=9)),
                ('icon_url', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='exercises',
            name='days',
            field=models.CharField(choices=[('SUN', 'SUN'), ('MON', 'MON'), ('TUE', 'TUE'), ('WED', 'WED'), ('THU', 'THU'), ('FRI', 'FRI'), ('SAT', 'SAT')], max_length=3),
        ),
    ]
