# Generated by Django 3.2.7 on 2023-05-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0011_auto_20230509_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='name',
            field=models.CharField(choices=[('SUN', 'sun'), ('MON', 'mon'), ('TUE', 'tue'), ('WED', 'wed'), ('THU', 'thu'), ('FRI', 'fri'), ('SAT', 'sat')], max_length=3),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='days',
            field=models.CharField(choices=[('SUN', 'sun'), ('MON', 'mon'), ('TUE', 'tue'), ('WED', 'wed'), ('THU', 'thu'), ('FRI', 'fri'), ('SAT', 'sat')], max_length=3),
        ),
    ]
