# Generated by Django 3.2.7 on 2023-06-21 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Workouts', '0012_auto_20230526_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('SUN', 'sun'), ('MON', 'mon'), ('TUE', 'tue'), ('WED', 'wed'), ('THU', 'thu'), ('FRI', 'fri'), ('SAT', 'sat')], max_length=27),
        ),
        migrations.CreateModel(
            name='Entry2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('reps', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ManyToManyField(to='Workouts.Exercises')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
