# Generated by Django 3.2.7 on 2023-08-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0014_category_numbertracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbertracker',
            name='Reps',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
