# Generated by Django 3.2.7 on 2023-08-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0015_numbertracker_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbertracker',
            name='Reps',
        ),
    ]
