# Generated by Django 3.2.7 on 2023-08-26 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0016_remove_numbertracker_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Workouts.category'),
            preserve_default=False,
        ),
    ]
