# Generated by Django 3.2.7 on 2023-08-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0017_exercises_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reps',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='units',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
