# Generated by Django 3.2.7 on 2023-08-27 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0019_auto_20230827_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='category',
        ),
    ]
