# Generated by Django 3.2.7 on 2023-08-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0021_auto_20230827_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbertracker',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='numbertracker',
            name='units',
            field=models.CharField(choices=[('lbs', 'LBS'), ('kg', 'KG')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
