# Generated by Django 3.2.7 on 2023-08-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0022_auto_20230827_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numbertracker',
            name='number',
        ),
    ]
