# Generated by Django 3.2.7 on 2023-08-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0023_remove_numbertracker_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('rep', models.IntegerField()),
                ('note', models.CharField(max_length=1000)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Workouts.category')),
            ],
        ),
    ]
