# Generated by Django 3.2.7 on 2023-08-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0024_trackerentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackerentry',
            name='parent_category',
        ),
    ]
