# Generated by Django 3.2.7 on 2023-09-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0026_auto_20230902_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerentry',
            name='nothing',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
