# Generated by Django 3.2.7 on 2023-09-04 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0027_trackerentry_nothing'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerentry',
            name='number_tracker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Workouts.numbertracker'),
            preserve_default=False,
        ),
    ]
