# Generated by Django 3.2.7 on 2023-09-04 18:24

from django.db import migrations, models
from django.utils import timezone  # Import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('Workouts', '0028_trackerentry_number_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackerentry',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),  # Use timezone.now as the default
            preserve_default=False,
        ),
    ]
